---
galaxy_info:
  role_name: kafka_strimzi
  author: autoresponse-team
  description: Deploys Strimzi Kafka operator and Kafka cluster into Kubernetes
  min_ansible_version: "2.14"

dependencies: []
